# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190609_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='name',
            new_name='base_form',
        ),
        migrations.AddField(
            model_name='word',
            name='original_form',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
