# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190609_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('article', 'question')]),
        ),
    ]
