# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190609_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='changed_form',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together=set([('article', 'word', 'is_title')]),
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set([('answer', 'method')]),
        ),
    ]
