# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20190610_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='added_date',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='positions_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='positions',
            field=models.CharField(max_length=2048),
        ),
    ]
