# Generated by Django 2.2.2 on 2019-06-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20190610_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='base_form',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
