# Generated by Django 2.2.2 on 2019-06-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20190616_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='positions_count',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
