# Generated by Django 2.2.2 on 2019-06-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20190616_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_words_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='title_words_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
