# Generated by Django 2.2.2 on 2019-07-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20190617_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='redirected_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirection_relationship', to='data.Article'),
        ),
    ]
