# Generated by Django 2.2.2 on 2019-10-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20191019_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='positions',
            field=models.CharField(max_length=20480),
        ),
    ]
