# Generated by Django 2.2.6 on 2019-11-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20191029_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occurrence',
            new_name='ArticleOccurrence',
        ),
        migrations.AlterField(
            model_name='word',
            name='changed_form',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('base_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_word', to='data.Word')),
                ('changed_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_word', to='data.Word')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='base_form',
        ),
        migrations.AddField(
            model_name='word',
            name='base_forms',
            field=models.ManyToManyField(related_name='changed_forms', through='data.WordForm', to='data.Word'),
        ),
        migrations.CreateModel(
            name='QuestionOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.CharField(max_length=20480)),
                ('positions_count', models.PositiveSmallIntegerField(db_index=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Question')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Word')),
            ],
            options={
                'unique_together': {('question', 'word')},
            },
        ),
    ]
