# Generated by Django 2.2.6 on 2019-11-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20191102_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='changed_form',
            new_name='value',
        ),
    ]
