# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20191102_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordform',
            unique_together={('changed_word', 'base_word')},
        ),
    ]
