# Generated by Django 2.2.6 on 2019-12-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20191102_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Article')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Method')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Question')),
            ],
        ),
    ]
