# Generated by Django 2.2.6 on 2019-12-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('question', 'article', 'method')},
        ),
    ]
