# Generated by Django 2.2.6 on 2019-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20191227_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='words',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='words_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
