# Generated by Django 3.0.2 on 2020-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_method_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='is_smaller_first',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
